name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: sakurasep/sakurasep@main
        with:
          blog_rss_link: https://blog.sakurasep.site/atom.xml
